### ISSUE TITLE
Make canopen_motor_node accessible via headers

### ISSUE THREAD

**Issue by mathias-luedtke** [ros-industrial/ros_canopen#101]
Move declarations and templates into dedicated headers.

**Comment by mistoll** [comment]
Is this what you expect: https://github.com/mistoll/ros_canopen/commit/d7b4154f7cf4e2c4dbee04b48b227d3cd9905208 ?

I'm going to send a PR as soon as it's ready

**Comment by mathias-luedtke** [comment]
Exactly :D

**Comment by mathias-luedtke** [comment]
solved by #226
