### ISSUE TITLE
Jade/Kinetic adaptions

### ISSUE THREAD

**Issue by mathias-luedtke** [ros-industrial/ros_canopen#161]
Mode switching needs to support mixed joint settings.

**Comment by mgruhler** [comment]
FYI, there has been a C++ API breaking change in `ros_control` for kinetic: https://github.com/ros-controls/ros_control/commit/afaf9403d1daf6e7f0a93e4a06aa9695e2883632

**Comment by mathias-luedtke** [comment]
That's what I meant with  "mixed joint settings" ;)

**Comment by mgruhler** [comment]
Ooops :-D

**Comment by mistoll** [comment]
I'd like to provide a pr for this.
It could be solved with a simple additional for loop over claimed_resources. Are there any doubts about that?
How do you want to select between the old and the new api? (Separate branch, conditional compilation)

**Comment by mathias-luedtke** [comment]
> How do you want to select between the old and the new api?

separate branch, `jade-devel` for jade and kinetic.

> It could be solved with a simple additional for loop over claimed_resources. Are there any doubts about that?

This works only for controllers without mixed modes.
However, it should be okay to just loop over the claimed_resources, but fail if more than one resource type is needed. (-> this supports all indigo-based controllers)

Mixed mode settings should be supported as well, but can be added later (#197).
