### ISSUE TITLE
Race condition in MotorChain::setup

### ISSUE THREAD

**Issue by mistoll** [ros-industrial/ros_canopen#181]
There's a race condition in MotorChain::setup.

MotorChain::setup calls RosChain::setup which initalizes the driver services (like init). But the mutex is not blocked by MotorChain::setup. So the service methods are executed after the call to RosChain with the rest of MotorChain::setup not beeing executed yet.

Thus there is a case, where the ControllerManagerLayer is not set up. 
Example log:

> [ INFO] [1465900080.354829180]: Initializing driver
> [ INFO] [1465900085.401722084]: Initializing XXX
> [ INFO] [1465900106.892959379]: Current state: 1 device error: system:0 internal_error: 0 (OK)
> [ INFO] [1465900106.897154048]: Current state: 2 device error: system:0 internal_error: 0 (OK)
> [ INFO] [1465900107.116479495]: Using fixed control period: 0.160000000

Here the last message is from MotorChain::setup, which should be finished before "Initializing driver".

**Comment by mathias-luedtke** [comment]
Thanks for reporting, I will have a look at it!

**Comment by mathias-luedtke** [comment]
@mistoll: Did you mean that  the services can be called before the rest of the motor chain was initialized? The code does not cover it..

As a quick fix the AsyncSpinner should be started after setup.

**Comment by mistoll** [comment]
@ipa-mdl Yes, that's what I ment. The mutex in RosChain prevents the service method from beeing executed while inside RosChain::setup. But for MotorChain that's not the case.

The Problem arises when you use the service like this:

```
client.waitForExistence(timeout);
client.call(trig);
```
