### ISSUE TITLE
Emergency handler disabled when devices does not have 0x1003 optional object.

### ISSUE THREAD

**Issue by JuliusGel** [ros-industrial/ros_canopen#184]
At the moment EMCYHandler listener will not be properly initialized if the device does not have 0x1003 object support.
This can be fixed by moving storage_->entry(num_errors_, 0x1003,0) call after interface->createMsgListener(...) initialization in EMCYHandler constructor.

**Comment by mathias-luedtke** [comment]
Reordering would result in missing `num_errors_` initilization, had to split the cases.
