### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_canopen#192]
More of a question, but I was wondering if/when the next release is planned? 0.6.4 is already more than a year old, and there appear to be quite some updates that are only found in the sources at the moment.

**Comment by gavanderhoorn** [comment]
I'm aware of #161. I'm specifically asking about Indigo.

**Comment by mathias-luedtke** [comment]
(duplicate of #189)

I don't have much time for testing right now.
I could release the current state (as it is running on Care-O-bot 4), but without the missing issue.

**Comment by gavanderhoorn** [comment]
I hadn't seen #189, my apologies.

I'll be the last to bug other devs about releases, but would there be much difference between users reporting bugs about _from source_ builds versus a released build?

**Comment by viktorvorobev** [comment]
I'm sorry, will there be any release for kinetic? I understand that there is some issues with ros_control, but still?

**Comment by mathias-luedtke** [comment]
> I'm sorry, will there be any release for kinetic? I understand that there is some issues with ros_control, but still?

A jade/kinetic release can be triggered after https://github.com/ros-industrial/ros_canopen/issues/161.
However, I cannot work on it right now.

**Comment by mathias-luedtke** [comment]
just released for indigo.
jade will follow after I was able to test it myself.
same for kinetic, but it's more complicated to test (still on 14.04).

**Comment by gavanderhoorn** [comment]
Very nice. Thanks for the effort.

Would you prefer to track jade/kinetic releases in a separate issue?

**Comment by mathias-luedtke** [comment]
"Next release" is a nice reminder ;)
The jade and kinetic releases are tracked in https://github.com/ros-industrial/ros_canopen/milestone/4 and https://github.com/ros-industrial/ros_canopen/milestone/5

**Comment by mathias-luedtke** [comment]
Jade release triggered: https://github.com/ros/rosdistro/pull/13399

**Comment by mathias-luedtke** [comment]
kinetic is released as well.
(https://github.com/ros/rosdistro/pull/13424)

**Comment by gavanderhoorn** [comment]
Awesome! :sparkles: :hamburger: :beers:

**Comment by mathias-luedtke** [comment]
I will close this issue after the next wave of releases

**Comment by mathias-luedtke** [comment]
Released again for indigo to kinetic :)
