### ISSUE TITLE
Group Position Controller

### ISSUE THREAD

**Issue by thiagodefreitas** [ros-industrial/ros_canopen#22]
Error description:
- When switching from Joint Trajectory Controller to Joint Position Controller, the 402 has an "invalid pointer".

Occurance(s) (when? Which hardware? How often?):
- Always during the tests on 11/12/2014
- Schunk LWA4d

How to reproduce the error:
- roslaunch schunk_lwa4d lwa4d.launch
- init
- rqt "stop Joint Trajectory Controller"
- rqt "start Group Position Controller"

**Comment by floweisshardt** [comment]
I don't think this fixes the issue. Because the same happened on cob4-2 arms which are not affected by this fix. @thiagodefreitas: please test on cob4-2 hardware. According to @ipa-mdl there need to be some change in the source code too.

**Comment by thiagodefreitas** [comment]
The change on the source code has no relation with this "fixed invalid pointer". To this controller mode change there is the need for the "PP mode"(hardware-side) what implies that the supported drive modes register should be changed:
  -DefaultValue=0x00000062
 +DefaultValue=0x00000063

what sets the PP mode bit. The fix for this specific problem is completed contained on this pull request.

The possible code change and the problem with cob4-2 should be addressed on a different issue.

**Comment by floweisshardt** [comment]
@thiagodefreitas please apply the same fix to https://github.com/ipa-fmw/cob_robots/blob/indigo_new_structure/cob_hardware_config/cob4-2/config/Schunk_0_63.dcf and open a new issue

**Comment by floweisshardt** [comment]
@thiagodefreitas: please check if cob4-2 and schunk_robots dcf is the same

**Comment by floweisshardt** [comment]
checked: is the same

**Comment by fmessmer** [comment]
Does this mean the joint_position_controller and the joint_group_position_controller work and can be used in this mode? If the positoin mode is not working there should be an issue documenting it...

**Comment by mathias-luedtke** [comment]
Profiled position mode should work, but I am not sure if it was tested actually.
This issue covers a bug that enabled to switch to position mode even if the driver did not offer it.
The fix just configures the support for the profiled position mode, the additional check that should prevent the switch to unconfigured modes will be implemented in #68
