### ISSUE TITLE
issues while trying the CAN exaamples

### ISSUE THREAD

**Issue by Ayushas2427** [ros-industrial/ros_canopen#223]
I am new to the topic of ROS CAN interfaces and trying to implement the following two package sources
https://github.com/ros-industrial/ros_canopen
and 
https://github.com/JCube001/socketcan-demo

Unfortunately, i m not able to implement any of them.
In first link of "ros_canopen", i am getting the following error while performing "catkin_make"

![screenshot from 2017-02-17 18 36 24](https://cloud.githubusercontent.com/assets/25845090/23066644/a28f8bdc-f541-11e6-873b-ed76716a2d71.png)
 
in the second link, Though everything was ok till i did "catkin_make' but the rosrun is showing the error of "package not found". I did the "source devel/setup.bash" which also did not give any error. So, why the rosrun is not able to be implemented? 

Thank you in advance.
Regards

Cross-post: http://answers.ros.org/question/254868/error-in-socketcan-demo/

**Comment by enricovillagrossi** [comment]
To solve the first problem you can try to install libmuparser with:
sudo apt-get install  libmuparser-dev

**Comment by mathias-luedtke** [comment]
Even better: use rosdep install..
(Or try the released version)

**Comment by Ayushas2427** [comment]
Thank you @enricovillagrossi. Your solution rectified my error.
@ipa-mdl , Thank you for your reply as well , since rosdep gets the required dependencies, will the help me to rectify my second issue as well?

**Comment by Ayushas2427** [comment]
Probably, here is where i am getting the error. When i perform "roscd <package name> " , everything goes fine, but when i did the same, for "socketcan_demo" package (which i explained in my second issue) , then it shows the error as "roscd: No such package/stack 'socketcan_demo'".

It means that my system is not able to find the package. What can i infer from this? and how can i resolve such issues?

Regards

**Comment by mathias-luedtke** [comment]
`socketcan-demo` (no catkin/ROS packages)  and `ros_canopen`  (catkin packages) are unrelated.

**Comment by Ayushas2427** [comment]
ok. Probably I was mixing two separate concepts. Thank you for rectifying

**Comment by mathias-luedtke** [comment]
seems to be off topic -> close
