### ISSUE TITLE
SocketCAN controller problems / Standby bug

### ISSUE THREAD

**Issue by thiagodefreitas** [ros-industrial/ros_canopen#23]
Error description:
- The node dies after sometime in standby. The error listed is controller problems on the 301.

Occurance(s) (when? Which hardware? How often?):
- After recovering the node, everything appeared to properly work, then after sometime in Standby without sending commands, the node died. Time not precisely recorded, but no more than 10 minutes.
- Schunk LWA4d with Peak-USB adapter

How to reproduce the error:
- Possible hint: Start the node, move the arm, then let it for 10+ minutes in standby mode.

**Comment by floweisshardt** [comment]
seems to be fixed now. Within 2 weeks of intensive testing on both cob4-2 arms never occured again.
