### ISSUE TITLE
Add CAN ID and mask to socketcan_bridge

### ISSUE THREAD

**Issue by 9a3eedi** [ros-industrial/ros_canopen#230]
It would be great if socketcan_bridge had the ability to only publish messages that has a certain CAN ID, specified by a rosparam. I can't seem to find any way of doing it other than creating a new node that filters out messages coming in/out from the bridge.

**Comment by mathias-luedtke** [comment]
If you just want to filter a single CAN ID, you can add it [here](https://github.com/ros-industrial/ros_canopen/blob/indigo-devel/socketcan_bridge/src/socketcan_to_topic.cpp#L46) easily .Otherwise more code needs to be written.

Yor're welcome to provide a pull request :)
