### ISSUE TITLE
CAT vehicle teleop mode error

### ISSUE THREAD

**Issue by Ayushas2427** [ros-industrial/ros_canopen#231]
I have used the tutorials of the [CAT Vehicle](http://cps-vo.org/node/31792) . i simulated the vehicle on gazebo and the vehicle performed well.

Now, i used the teleop mode to move the vehicle.
The TurtleBot teleop node is publishing Twist messages to /cmd_vel_mux/input/teleop ,and to convert them into /catvehicle/cmd_vel.

The following command is used for conversion:
_$ rosrun topic_tools relay /cmd_vel_mux/input/teleop /catvehicle/cmd_vel_

But the vehicle is not responding. May i please know where is the error?
Though,the vehicle is responding well with the "hard left turn" as shown in the [tutorial](http://cps-vo.org/node/26603).

Kindly help.
Best Regards

**Comment by mathias-luedtke** [comment]
How does this relate to `ros_canopen`?

**Comment by Ayushas2427** [comment]
Oh, I am very sorry. By mistake i posted it at the wrong location. Kindly take it as the first and final error from my side.

Shall remove it from here and will post it at a suitable location.

Best Regards

**Comment by Ayushas2427** [comment]
Closing the question. Re-posted it to the following link.
https://github.com/ros-industrial/industrial_experimental/issues/12

Regards
