### ISSUE TITLE
Error at robot_layer.cpp

### ISSUE THREAD

**Issue by epsilon425** [ros-industrial/ros_canopen#236]
Hi I'm trying to build the canopen package but I keep on getting errors concerning the
robot_layer.cpp. 

```
[ 97%] Building CXX object ros_canopen/canopen_motor_node/CMakeFiles/canopen_motor_node.dir/src/robot_layer.cpp.o
/home/paul/catkin_ws/src/ros_canopen/canopen_motor_node/src/robot_layer.cpp: In member function ‘virtual bool RobotLayer::prepareSwitch(const std::__cxx11::list<hardware_interface::ControllerInfo>&, const std::__cxx11::list<hardware_interface::ControllerInfo>&)’:
/home/paul/catkin_ws/src/ros_canopen/canopen_motor_node/src/robot_layer.cpp:378:63: error: ‘const struct hardware_interface::ControllerInfo’ has no member named ‘hardware_interface’
             if(g_interface_mapping.hasConflict(controller_it->hardware_interface
```
as you can see, hardware_interface cannot be referenced. Sorry for the trouble and thank you for your time!

**Comment by mathias-luedtke** [comment]
The issue tracker is no support forum, please use http://answers.ros.org for this purpose.

It looks like you are trying to build the `jade-devel` branch of `ros_canopen` against the `indigo` version of `ros_control`. The latter introduced an API break from `indigo` to `jade`, so please use corresponding versions.

**Comment by epsilon425** [comment]
thank you and I apologize for misusing the issue tracker
