### ISSUE TITLE
Movement after init

### ISSUE THREAD

**Issue by thiagodefreitas** [ros-industrial/ros_canopen#24]
Error description:
- After init, the arm moves(mostly only one joint)

Occurance(s) (when? Which hardware? How often?):
- Only sometimes
- Schunk LWA4d, cob4-2 arms

How to reproduce the error:
- bringup
- init

**Comment by floweisshardt** [comment]
seems to be fixed now. Within 2 weeks of intensive testing on both cob4-2 arms never occured again.
