### ISSUE TITLE
[socketcan_interface] interface.h isValid not const

### ISSUE THREAD

**Issue by vincentrou** [ros-industrial/ros_canopen#242]
We can not call the isValid function on a const can::Frame.
What about adding a const to this function which only read the can::Frame data ?

**Comment by mathias-luedtke** [comment]
Good catch! There is no reason for it to be non-const. 

It should get changed for `can::Frame::isValid` and `can::Header::isValid`.

**Comment by vincentrou** [comment]
Great thank you.
