### ISSUE TITLE
Timeout respawn from Controller Manager

### ISSUE THREAD

**Issue by thiagodefreitas** [ros-industrial/ros_canopen#25]
Error description:
- If the init service is not called, the Controller Manager re-spawns every minute

Occurance(s) (when? Which hardware? How often?):
- Always
- Elmo, Schunk, cob4-2

How to reproduce the error:
- bringup
- do not call init
- wait

**Comment by floweisshardt** [comment]
won't be fixed short term

**Comment by mathias-luedtke** [comment]
Migration to `controller_manager` script helped, see https://github.com/ipa320/cob_robots/issues/309
