### ISSUE TITLE
Queue size for publisher may be too small consider, 1000?

### ISSUE THREAD

**Issue by watters-torc** [ros-industrial/ros_canopen#253]
https://github.com/ros-industrial/ros_canopen/blob/3aa3ebbf4c2cc843c78813171854258692fe2606/socketcan_bridge/src/socketcan_to_topic.cpp#L38

This queue size will lead to dropped messages on a very active bus. Consider making the default large? Maybe 1000, or let it be configurable

**Comment by mathias-luedtke** [comment]
I would consider 1000 too large ;)

>  or let it be configurable

:+1:

**Comment by reidchristopher** [comment]
Added parameters to allow this to be configurable in #342
