### ISSUE TITLE
canopen_motor_node segfaults on eds file.

### ISSUE THREAD

**Issue by Timple** [ros-industrial/ros_canopen#256]
Upon parsing the eds file the canopen_motor_node segfaults.

I traced the issue back to the `parse_objects` function in the `objdict.cpp` file of canopen_master.

The issue seems to be with the 2007subX values in the eds file.

Parsing the eds file would be preffered, otherwise giving a usefull hint instead of a segfault would be a nice second.

EDS file attached.
[Engel_Drive_1_9.eds.txt](https://github.com/ros-industrial/ros_canopen/files/1482000/Engel_Drive_1_9.eds.txt)

**Comment by mathias-luedtke** [comment]
It is caused by `2007sub1`  which has datatype 1 (1bit booelan), but this is not supported by `ros_canopen`.
I would suggest to change the datatype to 5 (UNSIGNED8) in the EDS.

However, the parser needs some better error handling :-/
Not sure if we should just skip unsupported entries or crash with a proper message.

**Comment by mathias-luedtke** [comment]
With #258 it will still fail to load, but it will read:
> terminate called after throwing an instance of 'canopen::ParseException'
  what():  Cannot process 0x2007: Cannot process 0x2007sub1: std::bad_cast

**Comment by Timple** [comment]
Nice, we'll try putting the datatype to 5

edit, this worked! However the file itself states it is created by CANopen Design Tool 2.0.1. Shouldn't all output be expected to work? At least work on import side, supporting all is a whole other issue.

**Comment by Timple** [comment]
> terminate called after throwing an instance of 'canopen::ParseException'
> what(): Cannot process 0x2007: Cannot process 0x2007sub1: std::bad_cast

This helps a lot by pinpointing the issue to the 0x2007sub1 item, this took me a while. But then it does not hint a solution.

Would something like this be possible:
> terminate called after throwing an instance of 'canopen::ParseException'
> what(): Cannot process 0x2007: Cannot process 0x2007sub1: std::bad_cast, type is 0x01 which is not supported, supported types are: 0x05 0x09

**Comment by mathias-luedtke** [comment]
I have now altered the output to:

> terminate called after throwing an instance of 'canopen::ParseException'
what(): Cannot process 0x2007: Type of  0x2007sub1 does not match or is not supported

**Comment by Timple** [comment]
Works for me!
