### ISSUE TITLE
canopen_motor_node faults

### ISSUE THREAD

**Issue by changzhengwu** [ros-industrial/ros_canopen#265]
Thank you sir. 

I want to control my motor by ros_canopen. But something went wrong.
My motor is kollmorgen RGM and its protocol is also canopen.
My system is ubuntu 14.04 and the ROS version is indigo.

The process died when launch the node canopen_motor_node, It likely caused by the eds file. When parse the eds file, the process died.
I am new for the canopen eds file configuration. Can you help me. 

Here is the eds file
https://github.com/changzhengwu/eds-file/blob/master/Kollmorgen_RGM_V2.eds

Waiting for your help, thank you. @ipa-mdl @ipa-mdl @ipa-fxm

**Comment by Timple** [comment]
Sounds similar to this:
https://github.com/ros-industrial/ros_canopen/issues/256

If you are not familiar with debugging techniques like gdb, perhaps comment parts of your eds file until your node does not segfault ;-)

**Comment by mathias-luedtke** [comment]
@changzhengwu:

Do you get any message before the ROS node dies? (Try `roslaunch --screen`).
Did you run EDSChk?

@Timple:
The node does not segfault, it just sacrifies itself voluntarily ;)
