### ISSUE TITLE
PCAN, Socket can error on received frames on 

### ISSUE THREAD

**Issue by GeoDTN** [ros-industrial/ros_canopen#270]
We have frame errors sometimes(especially when we transmit
relatively longer files). We analysed the frames at hardware level at
receiver(microcontroller Colibri iMX6) with Canalyzer and Can case. But at hardware level there is no
error even when  the error happens.Then when we issued ifconfig can1, we see
frame error on received frames.There is no error on transmitted frames from microcontroller Colibri iMX6. 

![ifconf can1](https://user-images.githubusercontent.com/11195077/36890139-1d117034-1dfd-11e8-8405-2f9fbcef1179.PNG)

I guessed(not sure) the source of problem is kernel of the embedded module as
we proved there is no error on received frames at hardware level and
no error at all on transmitted frames from microcontroller(Colibri iMX6)
How can I solve it? It is urgent project and I am very worried about it.
Thank you in advance.

**Comment by mathias-luedtke** [comment]
As I have written before, these screenshot do hot help very much.
Which kernel driver are you using?
If you are using the one from the mainline kernel (recommended!), then you could try
```
ip -details -statistics link show can1
```
To read any errors at run-time, you can run
```
candump -l any,0~0,#FFFFFFFF
```

`socketcan_inteface` should log some information to stdout, too.
