### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by mathias-luedtke** [ros-industrial/ros_canopen#288]
`melodic_devel` should work, but needs some testing because of the interface chanages.

**Comment by kmhallen** [comment]
In the short term, could you bloom/release only the ```can_msgs``` package?

There are several packages that only depend on the ```can_msgs``` package that are waiting for its release:
http://wiki.ros.org/can_msgs?distro=kinetic

This could be implemented by creating a ```melodic.ignored``` file in the release repository temporarily:
https://github.com/DataspeedInc-release/dataspeed_can-release/blob/master/melodic.ignored
```
canopen_402
canopen_chain_node
canopen_master
canopen_motot_node
ros_canopen
socketcan_bridge
socketcan_interface
```

**Comment by mathias-luedtke** [comment]
> This could be implemented by creating a melodic.ignored file in the release repository temporarily:

Yes, but that would force me to tag a version for all packages in the source repository.

> There are several packages that only depend on the can_msgs package that are waiting for its release

I plan to test and release on [WRID18](https://rosindustrial.org/events/2018/7/10/world-ros-i-day).

**Comment by mathias-luedtke** [comment]
tested and released: https://github.com/ros/rosdistro/pull/18444
