### ISSUE TITLE
PDO communication parameters in EDS not work 

### ISSUE THREAD

**Issue by jacknlliu** [ros-industrial/ros_canopen#303]
We change the communication parameters of TPDO in EDS file, but it doesn't work in ros_canopen(we can see that no PDO message return after ros_canopen sent `080#` when we call service `driver/init`).

In EDS,
```ini
[1801sub2]
ParameterName=Transmission type TPDO 2
ObjectType=7
DataType=5
AccessType=RW
PDOMapping=0
DefaultValue=255
LowLimit=0
HighLimit=255
```

```
dcf_overlay:
  "1801sub2" : "1"
```

## Reference
- [canopen_master - ros wiki](http://wiki.ros.org/canopen_master?distro=melodic#EDS.2BAC8-DCF_files)
- [dcf_overlay for Node layer configuration](http://wiki.ros.org/canopen_chain_node?distro=melodic#Node_layer)

**Comment by mathias-luedtke** [comment]
Setting up the PDOs involves more than just setting the transmission type.

Please make sure that
* The PDO COB-ID is valid
* The EDS is correct (sometimes the defaults are wrong)
