### ISSUE TITLE
Socketbridge_socket_to_can Regarding

### ISSUE THREAD

**Issue by lab176344** [ros-industrial/ros_canopen#304]
Hello,

I am using Peak USB2CAN interface to get sensor information into ROS environment.

I am able to use socket_interface and check the frames via socket_dump. But when i use socket_bridge to convert the frames to topics i am getting a segmentation fault (core dumped) error.

![image](https://user-images.githubusercontent.com/23631821/46356024-35697b00-c662-11e8-8c96-bb29ff15e646.png)

Is this something related to the hardware i use or something else. I am using ROS kinetic distribtion in Ubuntu 16.04 system. Thank you in advance

**Comment by mathias-luedtke** [comment]
Please make sure that you have upgraded all packages to the latest version.
For further debugging please prefix it with gdb to get a stack trace.

**Comment by lab176344** [comment]
Thank you upgrading solved the error
