### ISSUE TITLE
joint_trajectory_controller not work with Interpolated Position mode

### ISSUE THREAD

**Issue by jacknlliu** [ros-industrial/ros_canopen#307]
The joint_trajectory controller with Interpolated Position mode didn't work, and no error report. The driver can open the motor brake. Using `rqt` can send the joint command, but the motor didn't move. And we add the topic publisher for `0x60C1sub1`, the value of `0x60C1sub1` can vary with the `rqt` joint command.

**Comment by jacknlliu** [comment]
And what about using joint_trajectory_controller with CSP mode?

**Comment by mathias-luedtke** [comment]
I can assure you that the `joint_trajectory_controller` works fine with IP mode.
I have never tested CSP mode. It should work, but interpolation is desirable for smooth motion.

Please review your manual again and set-up the IP mode properly (command type, buffering policy, interpolation period etc).
`ros_canopen` only supports commanding positions (as generated by the trajectory controller).

I don't think that this is an issue with `ros_canopen`, so I will close this issue.

**Comment by jacknlliu** [comment]
@ipa-mdl Our Kollmorgen RGM drive written the interpolation position to object `0x60C sub0`, and interpolation time to object `0x60C1sub1`, velocity to `0x60C1sub2`. But the ros_canopen write the interpolation position to `0x60C1sub1`(and write the `velocity` and `time` to ?)

Can we only modify the subindex at the following line to adapt the device?

https://github.com/ros-industrial/ros_canopen/blob/410984dc5ec8be0e41686a42618fdfa7c037e570/canopen_402/include/canopen_402/motor.h#L209

**Comment by jacknlliu** [comment]
@ipa-mdl  Thanks for your advice for IP mode. `ros_canopen` write the interpolation `position` to object `0x60C1sub1`, does it also write the interpolation time and velocity?

**Comment by mathias-luedtke** [comment]
> does it also write the interpolation time and velocity?

You can specify the interpolation period in the DCF.
Commanding velocities (through `0x60C1sub2`) is not supported.

Set `0x60C0` to 0 (linear interpolation).

**Comment by jacknlliu** [comment]
Thanks very much. After set `0x60C0` to `0` not the default `-1`, it has response. But we get an exception behaviour. The motor move quickly and won't stop. Should the joint trajectory controller send the current actual position to keep the position after load the controller in the normal state?

Here we use IP mode with the joint trajectory controller, and the following are the result from `candump can0`. 
```
  can0  181   [3]  37 17 06 (status word, mode of operation)
  can0  281   [4]  24 A9 BE FF (actual position)
  can0  381   [4]  00 00 00 00 (actual velocity)
  can0  481   [2]  06 00 (actual torque)
  can0  201   [7]  0F 01 07 00 00 00 00 (control word, mode of operation, 60c1sub1) (switch to mode 07, after enable motor)
  can0  080   [0] 
  can0  181   [3]  37 07 07
  can0  281   [4]  1E A9 BE FF
  can0  381   [4]  00 00 00 00
  can0  481   [2]  04 00
  can0  201   [7]  1F 00 07 5D BE BF FF (send interpolation position `5D BE BF FF`)
  can0  080   [0] 
  can0  181   [3]  37 52 07
  can0  281   [4]  22 A9 BE FF
  can0  381   [4]  00 00 00 00
  can0  481   [2]  01 00
  can0  201   [7]  1F 00 07 A1 C8 BF FF (send IP `A1 C8 BF FF`)
  can0  080   [0] 
  can0  181   [3]  37 52 07
  can0  281   [4]  20 A9 BE FF
  can0  381   [4]  00 00 00 00
  can0  481   [2]  05 00
  can0  201   [7]  1F 00 07 E5 D2 BF FF (send IP `E5 D2 BF FF`)
  can0  080   [0] 
  can0  181   [3]  37 52 07
  can0  281   [4]  24 A9 BE FF
  can0  381   [4]  00 00 00 00
  can0  481   [2]  06 00
  can0  201   [7]  1F 00 07 2A DD BF FF (send IP `2A DD BF FF`)
  can0  080   [0] 
  can0  181   [3]  B7 5A 07
  can0  281   [4]  79 A9 BE FF
  can0  381   [4]  34 E8 0A 00
  can0  481   [2]  31 09
  can0  201   [7]  1B 00 07 2A DD BF FF (send IP `2A DD BF FF`)
  can0  080   [0] 
  can0  181   [3]  97 5B 07
  can0  281   [4]  67 AF BE FF
  can0  381   [4]  EC B4 5E 00
  can0  481   [2]  21 09
  can0  201   [7]  1B 01 07 2A DD BF FF (send IP `2A DD BF FF`)
  can0  080   [0] 
  can0  181   [3]  97 5B 07
  can0  281   [4]  77 BB BE FF
  can0  381   [4]  46 C1 A8 00
  can0  481   [2]  65 03
```

**Comment by jacknlliu** [comment]
> The motor move quickly and won't stop.

We find that the object `0x60c2` about IP mode should be disabled in CSP mode.
