### ISSUE TITLE
Timestamp issue in SocketCANToTopic() with ros::Time::now();

### ISSUE THREAD

**Issue by Beck-Sisyphus** [ros-industrial/ros_canopen#309]
Dear ros_canopen developer,

The SocketCANToTopic() put the timestamp using ros::Time::now() instead of the hardware interrupt time from the socket CAN. The ROS can results multiple topics to be published with the same time, and mess up the timestamp for the sensor. Please consider to change the time stamp to the "Frame" time instead.

Thanks,
Beck

**Comment by gavanderhoorn** [comment]
Why did you close this @Beck-Sisyphus ?
