### ISSUE TITLE
Mode 7 is not available for rig1_plate_joint

### ISSUE THREAD

**Issue by CccYunxiao** [ros-industrial/ros_canopen#311]
I want to use Interpolated Position mode to motors ｍｏｔｉｏｎ, ｓｏ i use the node canopen_motor_node with operation modes ID.7

There is an error：　

`[ERROR] [1543196493.734653465]: Mode 7 is not available for rig1_plate_joint
[ERROR] [1543196493.734755167]: Could not switch controllers. The hardware interface combination for the requested controllers is unfeasible.
[ERROR] [1543196493.735180]: Failed to start controllers: joint_trajectory_controller`

Ｓｏ hardware_interface::PositionJointInterface can not accept IP mode(ID.7) ? Right?

Why i will meet this error when use the canopen_test_utils package? Who can enlighten me? Thx very much!!

**Comment by CccYunxiao** [comment]
@tfoote @ipa-mdl

**Comment by CccYunxiao** [comment]
@floweisshardt

**Comment by CccYunxiao** [comment]
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
    - rig1_plate_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    rig1_plate_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7

**Comment by mathias-luedtke** [comment]
This is an issue tracker and no support forum.
In addtion `canopen_test_utils` is mostly for internal usage and intentionally not part of this repository.
If you need help in setting up your device, you may find a solution on [ROS answers](https://answers.ros.org).
If none of the existing answers work for you, you can ask specificially over there.

Please do not tag others here, especially if they are unrelated.
Thanks!
