### ISSUE TITLE
Communication problems using PEAK pci

### ISSUE THREAD

**Issue by cpaniagua1** [ros-industrial/ros_canopen#312]
Hello,

I'm using a PEAK pci module to send messages from my PC to another one. Suddently the transmission starts sending zeros and the only way to recover the normal operation is unplugging and plugging the CAN. 

Could anybody help me?

Thanks in advance!

**Comment by mathias-luedtke** [comment]
I don't think that this issue is related to our software.
It might be an electrical problem or some issue with your kernel driver.
If you cannot figure it out, you could contact PEAK directly.
