### ISSUE TITLE
Stop Joint Trajectory Controller when the action aborts

### ISSUE THREAD

**Issue by thiagodefreitas** [ros-industrial/ros_canopen#32]
Error description:
- If the Joint Trajectory Controller Action is aborted, then stop

Occurance(s) (when? Which hardware? How often?):
- Always
- Elmo, Schunk, cob4-2

How to reproduce the error:
- bringup
- init
- move(within a big range in between a short period of time, what implies V>Vmax)

**Comment by floweisshardt** [comment]
todo: check if joint_trajectory_controller behaves the same in simulation

**Comment by mathias-luedtke** [comment]
Must be fixed in ros_controllers: https://github.com/ros-controls/ros_controllers/issues/48
