### ISSUE TITLE
problem with firmware version

### ISSUE THREAD

**Issue by KaushalkumarPatel** [ros-industrial/ros_canopen#329]
Hello to all,

I am using schunk lwa4p arm with ros kinetic in ububtu 16.04. 

I have found that this ros_canopen works only for 63 firmware version. but in my arm both schunk ERBo ERB 145 modules at 67 firmware version and remaining modules are at 63.

What changes I have to make to use this ros_canopen package ?

@ipa-mdl

**Comment by mathias-luedtke** [comment]
This is related and might help: https://answers.ros.org/question/266252/schunk_lwa4p-initialization-error-with-ros_canopen/?answer=266365#post-id-266365.

However, this is the issue tracker for `ros_canopen` and no support site. I will close this issue now.
