### ISSUE TITLE
SimpleSyncLayer does not handle overflow sync counter 

### ISSUE THREAD

**Issue by benmaidel** [ros-industrial/ros_canopen#348]
Setting the overflow param to any value between 0 and 240 should result into a counter value inside the sync frame. The external sync (bcm_sync) is doing it correctly but the internal sync (SimpleSyncLayer) is not.

relevant code section: https://github.com/ros-industrial/ros_canopen/blob/melodic-devel/canopen_master/src/master_plugin.cpp#L53

**Comment by mathias-luedtke** [comment]
> Setting the overflow param to any value between 0 and 240 should result into a counter value inside the sync frame. 

Actually, between 2 and 240. `0` (default) deactivates the counter, `1` is reserved.
