### ISSUE TITLE
Not able to publish on sent_message for can_msg/Frame

### ISSUE THREAD

**Issue by Prj1508** [ros-industrial/ros_canopen#353]
Hi,
I am trying to publish into sent_message topic for the message type can_msg/Frame with the following command:

rostopic pub -r 10 /sent_messages can_msgs/Frame 'header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
id: 0x29F
is_rtr: false
is_extended: false
is_error: false
dlc: 8
data: "\x53\x70\x40\x00\x00\x00\x40\x6a"
'
I do not get any error, but when I listen to this thru rostopic echo, it does not show anything. 

To make sure it is set up right, i sent this command and it display correctly in echo terminal;

rostopic pub -r 10 /sent_message std_msgs/String 'hello'

Please let me know what am I doing wrong. 

Thanks

**Comment by mathias-luedtke** [comment]
The message format of `rostopic` auto-complete is wrong for some reason.
Please try passing he bytes as an array: `data: [1,2,3,4,5,6,7,8]` 

PS: This is a bug tracker only. If you need further support you might post a question on [ROS answers](https://answers.ros.org). I will close this issue.
