### ISSUE TITLE
ROS Error : Failed to send message

### ISSUE THREAD

**Issue by Prj1508** [ros-industrial/ros_canopen#365]
I get this message when I publish on sent_messages topic of socketcan_bridge node. I see that this is getting published properly, but is not being sent to the can bus ( topic to socketcan issue). CAN is working properly and I can see traffic thru candump. 

In topic to socketcan code, I see that there is a boolean flag which sends this message when fault. Is this to do with overflow of data I am trying to stuff into available data bits of the message

I am using Ubuntu 16.04 and ROS Kinetic

thanks for your help

**Comment by mathias-luedtke** [comment]
I would suspect that your frame is not valid.
How do you publish the data?

**Comment by Prj1508** [comment]
i am publishing thru a 10ms timer callback. All CAN data byte stuffing is happening in another subscriber call back which updates a global variable of type can_msgs::Frame. This variable is then published thru a 10ms timer callback.

**Comment by Prj1508** [comment]
this issue is same as #366.

**Comment by Prj1508** [comment]
I didn’t not capture console output with —screen option. will do so today and revert

**Comment by mathias-luedtke** [comment]
> this issue is same as 306.

306 or 366?

**Comment by Prj1508** [comment]
Sorry, 366

**Comment by mathias-luedtke** [comment]
duplicate of #366
