### ISSUE TITLE
When positon mode, driver run previous position instead of the current position set on 0x607A

### ISSUE THREAD

**Issue by clm330** [ros-industrial/ros_canopen#373]
When I sent position command to driver in position mode, the motor always rotate to previous position set on **0x607A**.

`ros-canopen version: kinetic`
`controller:joint_state_controller/JointStateController`

Graph:
See the graph. When 0x6040 rising delay, the driver always run to previous position.
![Screenshot from 2019-12-22 16-14-15](https://user-images.githubusercontent.com/6710845/71319331-dc406e00-24d7-11ea-8b2f-98084cd6ce51.png)

It seems when rising delay, the **0x607A** still not update.
I try to  set a delay at the rising delay to solve this problem but it seems no effect.

cpp file: canopen_402/src/motor.cpp
function: Motor402::handleWrite(LayerStatus &status, const LayerState &current_state)

```
            if(okay) {
                // --------add delay------------
                if(this->mode_id_ == 1){
                    sleep(0.1);
                }
                // --------add delay------------
                std::cout<<"~(1<<Command402::CW_Halt) : "<<std::hex << static_cast<int>(~(1<<Command402::CW_Halt))<<std::endl;
                control_word_ &= ~(1<<Command402::CW_Halt);
                std::cout<<"drive_id :"<<this->name<<" control word :"<<std::hex << static_cast<int>(control_word_)<<std::endl;
            }
```

Maybe I added the delay in the wrong place, can tell me where to add the delay. It may help debug.
Thanks.

**Comment by mathias-luedtke** [comment]
> See the graph

Are you sure that the motor does not just drive into the wrong direction?
Could you prepare a graph that steps the position up?

> I try to set a delay at the rising delay

If you add a delay to `handleWrite`, you prolong the communication cycle. These function should never block like this.

**Comment by clm330** [comment]
@ipa-mdl 

> Are you sure that the motor does not just drive into the wrong direction?
> Could you prepare a graph that steps the position up?

See this gragp.
I sent the position first time, but nothing happened.
It can prove that the driver always goes to the previous position.
![Screenshot from 2019-12-23 09-40-05](https://user-images.githubusercontent.com/6710845/71330472-46a0ef00-2568-11ea-87e3-763b541a0d61.png)


This graph is candump -td about 401(mapping `0x607A`), I sent 3.3(1487) to `0x607A`. 
Does time affect the program??
![Screenshot from 2019-12-23 17-16-44](https://user-images.githubusercontent.com/6710845/71349011-dfeff580-25a8-11ea-804f-3662cf0dc089.png)


This is graph is candump -ta about 401.
![Screenshot from 2019-12-23 17-45-45](https://user-images.githubusercontent.com/6710845/71350673-c0f36280-25ac-11ea-9596-585cec95cc56.png)
This graph show sent control_word(201) less than one millisecond after sending position msg.
According to the figure above, the total time to send the position is 98 ms. 
Can the driver receive the position correctly msg before running the command?


> If you add a delay to handleWrite, you prolong the communication cycle. These function should never block like this.

**About delay.**
Sometime I found `0x6040` rising delay before position cmd `0x607A`  changed.
![Screenshot from 2019-12-24 15-04-15](https://user-images.githubusercontent.com/6710845/71399714-8565a080-265f-11ea-9dbe-c09eaec6b2bd.png)

I think it may be that when the position information is rising delay(0x6064), 0x607A has not received the latest location information, so the driver always runs to the previous position.
Can I add a delay to control_word (0x6040) for bebug ? If can add, where I should add a delay in source code?

**Comment by clm330** [comment]
In velocity mode, I find similar phenomenon.
I set interval_ms to 500.
See the graph.

![Screenshot from 2019-12-23 14-32-50](https://user-images.githubusercontent.com/6710845/71340270-28031e00-2591-11ea-922f-8056a3480fca.png)


The actual velocity ` 0x606C` begen to change from 0 after two time interval_ms, even if set interval_ms to shorter time interval.

Is this problem  same with the above?

**Comment by clm330** [comment]
Set the Transmission type to 255, it works normally.
