### ISSUE TITLE
CAN 2.0b physical layer

### ISSUE THREAD

**Issue by JadTawil-theonly** [ros-industrial/ros_canopen#379]
2.0b corresponds to 29 bit CAN-ids

Does this driver support Canopen devices using the CAN 2.0b physical layer?

**Comment by mathias-luedtke** [comment]
The `socketcan_*` packages support extended frames, but the `canopen_*` do  not (yet?).

**Comment by JadTawil-theonly** [comment]
Hey Mathias,

I tried running the driver with a 2.0b device, and it seemed to work fine (publishing to pdos, and reading from pdos, as well as the ros-control layer). Is this surprising to you?

**Comment by mathias-luedtke** [comment]
As long as you did not use extended frames for addressing, it not really a surprise.
Most (all?) modern CAN devices should support both.
