### ISSUE TITLE
Init for Schunk fails

### ISSUE THREAD

**Issue by floweisshardt** [ros-industrial/ros_canopen#38]
Error description:
- arm cannot be initialized (init service is blocking forever)

Occurance(s) (when? Which hardware? How often?):
- sometimes (often multiple restarts of bringup helps)

How to reproduce the error:
- bringup
- init --> blocks sometimes and throws "boost::exception_detail::clone_implboost::exception_detail::error_info_injector<ipa_canopen::PointerInvalid >"

Log:
[ INFO] [1416557367.643892202]: Initializing XXX
[ INFO] [1416557367.644528496]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1416557367.644858421]: Current state: 2 device error: system:0 internal_error: 0 (OK)
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
[ INFO] [1416557367.837664433]: waitForService: Service [/sensorring/controller_manager/load_controller] has not been advertised, waiting...
[ INFO] [1416557367.912405622]: waitForService: Service [/arm_left/controller_manager/load_controller] has not been advertised, waiting...
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
[ INFO] [1416557369.322104614]: waitForService: Service [/arm_left/controller_manager/load_controller] is now available.
[ INFO] [1416557369.876763953]: joint_trajectory_controller loaded
[ INFO] [1416557370.349831145]: waitForService: Service [/arm_right/controller_manager/load_controller] has not been advertised, waiting...
[ INFO] [1416557370.526872957]: joint_group_position_controller loaded
[ INFO] [1416557370.866774447]: joint_group_velocity_controller loaded
[ INFO] [1416557370.886587375]: Switched Controllers
[ERROR] [1416557370.896748454]: /u/fmw/git/care-o-bot/src/ros_canopen/ipa_canopen_master/include/ipa_canopen_master/objdict.h(342): Throw in function void ipa_canopen::ObjectStorage::Entry<T>::set(const T&) [with T = int]
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<ipa_canopen::PointerInvalid >
std::exception::what: std::exception

[ INFO] [1416557370.907292199]: Switched Controllers
[ERROR] [1416557371.897297268]: /u/fmw/git/care-o-bot/src/ros_canopen/ipa_canopen_master/src/pdo.cpp(270): Throw in function void ipa_canopen::PDOMapper::RPDO::sync()
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<ipa_canopen::TimeoutException >
std::exception::what: std::exception

[ INFO] [1416557372.860173446]: waitForService: Service [/sensorring/controller_manager/load_controller] has not been advertised, waiting...
[ERROR] [1416557372.897410983]: /u/fmw/git/care-o-bot/src/ros_canopen/ipa_canopen_master/src/pdo.cpp(270): Throw in function void ipa_canopen::PDOMapper::RPDO::sync()
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<ipa_canopen::TimeoutException >
std::exception::what: std::exception

[ERROR] [1416557373.898152641]: /u/fmw/git/care-o-bot/src/ros_canopen/ipa_canopen_master/src/pdo.cpp(270): Throw in function void ipa_canopen::PDOMapper::RPDO::sync()
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<ipa_canopen::TimeoutException >
std::exception::what: std::exception

[ERROR] [1416557374.898411403]: /u/fmw/git/care-o-bot/src/ros_canopen/ipa_canopen_master/src/pdo.cpp(270): Throw in function void ipa_canopen::PDOMapper::RPDO::sync()
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<ipa_canopen::TimeoutException >
std::exception::what: std::exception

**Comment by floweisshardt** [comment]
another log:

[ INFO] [1416557762.694235436]: Initializing XXX
[ INFO] [1416557762.694965471]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1416557762.695160888]: Current state: 2 device error: system:0 internal_error: 0 (OK)
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
[ INFO] [1416557764.784138229]: waitForService: Service [/arm_left/controller_manager/load_controller] is now available.
[ INFO] [1416557765.346526415]: joint_trajectory_controller loaded
[ INFO] [1416557766.108562520]: waitForService: Service [/arm_right/controller_manager/load_controller] has not been advertised, waiting...
[ INFO] [1416557766.116804705]: joint_group_position_controller loaded
[ INFO] [1416557766.586659529]: joint_group_velocity_controller loaded
[ERROR] [1416557766.606530527]: /u/fmw/git/care-o-bot/src/ros_canopen/ipa_canopen_master/include/ipa_canopen_master/objdict.h(342): Throw in function void ipa_canopen::ObjectStorage::Entry<T>::set(const T&) [with T = int]
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<ipa_canopen::PointerInvalid >
std::exception::what: std::exception

[ INFO] [1416557766.606534255]: Switched Controllers
[ INFO] [1416557766.627181025]: Switched Controllers
[ERROR] [1416557767.606973595]: /u/fmw/git/care-o-bot/src/ros_canopen/ipa_canopen_master/src/pdo.cpp(270): Throw in function void ipa_canopen::PDOMapper::RPDO::sync()
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<ipa_canopen::TimeoutException >
std::exception::what: std::exception

[ERROR] [1416557768.607622302]: /u/fmw/git/care-o-bot/src/ros_canopen/ipa_canopen_master/src/pdo.cpp(270): Throw in function void ipa_canopen::PDOMapper::RPDO::sync()
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<ipa_canopen::TimeoutException >
std::exception::what: std::exception

**Comment by floweisshardt** [comment]
a successfully try look like this:

[ INFO] [1416560099.650839736]: Initializing XXX
[ INFO] [1416560099.651499383]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1416560099.651946326]: Current state: 2 device error: system:0 internal_error: 0 (OK)
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
[ INFO] [1416560102.517563644]: waitForService: Service [/arm_left/controller_manager/load_controller] has not been advertised, waiting...
[ INFO] [1416560107.569856647]: waitForService: Service [/arm_left/controller_manager/load_controller] is now available.
[ INFO] [1416560109.824303968]: joint_trajectory_controller loaded
[ INFO] [1416560110.164212122]: joint_group_position_controller loaded
[ INFO] [1416560110.494032642]: joint_group_velocity_controller loaded
[ INFO] [1416560110.503989014]: Switched Controllers
[ INFO] [1416560110.513967290]: Switched Controllers
[ INFO] [1416560110.524107548]: Switched Controllers

**Comment by floweisshardt** [comment]
fixed with only loading trajectory controller at startup. see https://github.com/ipa-fmw/cob_control/commit/271a72af72efacf4c29cf23273cfe970eebf7e3c

**Comment by felixwatzlawik** [comment]
Hi,

I still got this bug. How can I solve it on my System?
