### ISSUE TITLE
Release ros_canopen into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-industrial/ros_canopen#389]
Would you mind releasing `ros_canopen` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 19 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by mathias-luedtke** [comment]
release: https://github.com/ros/rosdistro/pull/24764
