### ISSUE TITLE
Question:Usage of socketcan_bridge

### ISSUE THREAD

**Issue by ashwinsarvesh** [ros-industrial/ros_canopen#395]
Hello,

 I want to convert a ROS topic to can messages and send it to a CAN bus using a USB to CAN adapter(eg.PEAK CAN adapter).
Can I do this with socketcan_bridge?
Basically to extract a software value in the form of ROS topic as a can message to send it to an external device.

Please help me.

**Comment by mathias-luedtke** [comment]
`socketcan_bridge` only processes `can_msgs/Frame` messages.
To support your custom format, you have to write your own node using `socketcan_interface`.

If you need further support, you might find hints or post you own question on [ROS answers](https://answers.ros.org/).
GitHub issues are meant for bug reports and feature requests only.
