### ISSUE TITLE
Error when a joint group velociy message is continuously published(e.g. during init)

### ISSUE THREAD

**Issue by thiagodefreitas** [ros-industrial/ros_canopen#40]
Error description:
Segmentation fault when publishing a velocity message before moving the arm with Trajectory Controller

Occurance(s) (when? Which hardware? How often?):
most times
cob4-2 arms

How to reproduce the error:
    bringup
    init
    do not use(move the arm with) trajectory controller
   publish velocity message

Propertly initialized module
[ INFO] [1416591307.171674507]: waitForService: Service [/arm_left/controller_manager/load_controller] is now available.
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffc8996700 (LWP 9766)]
[ INFO] [1416591307.552940521]: joint_trajectory_controller loaded
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffa7de7700 (LWP 9769)]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[ INFO] [1416591307.862866977]: joint_group_position_controller loaded
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[ INFO] [1416591308.042937821]: joint_group_velocity_controller loaded
Enter mode7
Enter mode7
Enter mode7
Enter mode7
Enter mode7
Enter mode7
Enter mode7
[ INFO] [1416591308.192893655]: Switched Controllers. From no_stop_controller_defined to joint_trajectory_controller
---Type <return> to continue, or q <return> to quit---

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe4ff9700 (LWP 9752)]
0x00007fffa71b8d55 in forward_command_controller::ForwardJointGroupCommandController<hardware_interface::VelocityJointInterface>::commandCB (this=0x7fffd0076c80, msg=...)
    at /u/fmw/git/care-o-bot/src/ros_controllers/forward_command_controller/include/forward_command_controller/forward_joint_group_command_controller.h:128
128     {  commands_[i] = msg->data[i];  }
(gdb) bt
#0  0x00007fffa71b8d55 in forward_command_controller::ForwardJointGroupCommandController<hardware_interface::VelocityJointInterface>::commandCB (this=0x7fffd0076c80, msg=...)

```
at /u/fmw/git/care-o-bot/src/ros_controllers/forward_command_controller/include/forward_command_controller/forward_joint_group_command_controller.h:128
```
#1  0x00007fffa73de12c in operator() (a0=..., this=<optimized out>)

```
at /usr/include/boost/function/function_template.hpp:767
```
#2  boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<std_msgs::Float64MultiArray_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<std_msgs::Float64MultiArray_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<std_msgs::Float64MultiArray_<std::allocator<void> > const>)

```
(function_obj_ptr=..., a0=...) at /usr/include/boost/function/function_template.hpp:153
```
#3  0x00007fffa73de5d1 in operator() (a0=..., this=0x7fffd00773a8)

```
at /usr/include/boost/function/function_template.hpp:767
```
#4  ros::SubscriptionCallbackHelperTboost::shared_ptr<std_msgs::Float64MultiArray_<std::allocator<void > const> const&, void>::call (this=0x7fffd00773a0, params=...)

```
at /opt/ros/indigo/include/ros/subscription_callback_helper.h:144
```
#5  0x00007ffff69d5498 in ros::SubscriptionQueue::call() ()

**Comment by floweisshardt** [comment]
please use the template? Error description? Which hardware? how to reproduce? What needs to be changed?

**Comment by thiagodefreitas** [comment]
@ipa-fmw I have updated the description of the problem.

**Comment by thiagodefreitas** [comment]
This is fixed
