### ISSUE TITLE
Failure to run socketcan_interface socketcan_dump

### ISSUE THREAD

**Issue by RuihanGao** [ros-industrial/ros_canopen#401]
Hi, I use ros-kinetic and try to read data from esd can/usb2 connector but get the following error messages. Anyone can kindly help? Thanks!
```
rosrun socketcan_interface socketcan_dump can0
ERROR: state=1 internal_error=0('OK') asio: system:0
ERROR: state=2 internal_error=0('OK') asio: system:0
```

**Comment by mathias-luedtke** [comment]
Don't worry, this is normal.
In the devel version it reads "STATE" instead of "ERROR" (https://github.com/ros-industrial/ros_canopen/pull/372), but I did not push a new release yet.

**Comment by mathias-luedtke** [comment]
New release: https://github.com/ros/rosdistro/pull/26274
