### ISSUE TITLE
[problem] Device not set

### ISSUE THREAD

**Issue by Jinhwi-Lee** [ros-industrial/ros_canopen#405]
Hello,
I am trying to control the motor via socketcan and ros_canopen.
But I have a problem
I tried to connect socketcan by

$ modprobe can_dev
$ modprobe can
$ modprobe can_raw
$ sudo ip link set can0 type can bitrate 500000
$ sudo ip link set up can0
(URL: https://en.wikipedia.org/wiki/SocketCAN)

And 

$ roscore
$ rosrun canopen_chain_node canopen_chain_node
[ERROR] : Device not  set

I use Kvaser V2 canopen module.

Thank you.

**Comment by mathias-luedtke** [comment]
You have pass the CANopen "device", in your case `can0`. See the [wiki](http://wiki.ros.org/canopen_chain_node#Configuration) as well.
