### ISSUE TITLE
cannot initialize after connecting with Schunk software

### ISSUE THREAD

**Issue by floweisshardt** [ros-industrial/ros_canopen#41]
After setting new limits with the Schunk software, it is not possible to initialize with ROS again. This can be solved with multiple (>3x) restarts of bringup+init

**Comment by thiagodefreitas** [comment]
We need to keep observing this issue. However, it did not occur due to the configuration from yesterday.

**Comment by floweisshardt** [comment]
seems to be OK now as it didn't occur any more. I'll close this.

**Comment by thiagodefreitas** [comment]
Seems to be solved. Worked already 10 times in a row.
