### ISSUE TITLE
send different control word to different nodes when closing node.

### ISSUE THREAD

**Issue by clm330** [ros-industrial/ros_canopen#418]
Hello,
I have a differential wheel robot which have two drivers.
I map 6040 and 6060 as follow:
**1600sub1: 0x60400010**
**1600sub2: 0x60600008**
Why RPDOs( 201, 202 as follow images) to two drivers is different when **rosnode kill /driver**.
![image](https://user-images.githubusercontent.com/6710845/104000510-4f974980-51d9-11eb-872c-60406d6b369a.png)

Looking forward to your reply.

**Comment by mathias-luedtke** [comment]
Each drive has its own state (as encoded in the status word) and the control word is used to modify it.
Both can vary between drives, nothing to worry about.

If you want to find out more about the difference, you have to decode the [individual bits](https://github.com/ros-industrial/ros_canopen/blob/melodic-devel/canopen_402/include/canopen_402/motor.h#L84).

**Comment by clm330** [comment]
Thanks.
