### ISSUE TITLE
add diagnostics

### ISSUE THREAD

**Issue by floweisshardt** [ros-industrial/ros_canopen#43]
- should give some human readable information about the status of each module and each chain.
- should at least report overall, status, bus error, under voltage error (e.g. EMStop active)

**Comment by floweisshardt** [comment]
tested on cob4-2: diagnostics ok

@thiagodefreitas: missing diagnostics change to warning for `halt`

@ipa-mdl: fix crash on shutdown

**Comment by floweisshardt** [comment]
will be solved within #68

**Comment by floweisshardt** [comment]
fixed in https://github.com/ipa320/ros_canopen/commit/ec606f98f537c670530b022589c36641a1e27674

**Comment by mathias-luedtke** [comment]
@thiagodefreitas: 402 diagnostics are still missing.
