### ISSUE TITLE
How to skip entering homing mode when I call driver/init service of canopen_motor_node(canopen_chain_node)?

### ISSUE THREAD

**Issue by ye-luo-xi-tui** [ros-industrial/ros_canopen#439]
Hi,I find that the `driver/init` would try to make my device enter homing mode.If it failed,init failed too.But manufacturer didn't provide homing method which I need.And I want to make my device home in nonnormal method.So how can I skip the step that enter homing mode of the service `driver/init`?

**Comment by mathias-luedtke** [comment]
You have 3 options:

* set homing method (`0x6098`) to 0, make it the `DefaultValue` in EDS
* remove the homing mode from supported drive mode `0x6502`
* implement your own homing ([example](https://github.com/ipa320/cob_driver/blob/kinetic_dev/cob_elmo_homing/))

**Comment by ye-luo-xi-tui** [comment]
> You have 3 options:
> 
> * set homing method (`0x6098`) to 0, make it the `DefaultValue` in EDS
> * remove the homing mode from supported drive mode `0x6502`
> * implement your own homing ([example](https://github.com/ipa320/cob_driver/blob/kinetic_dev/cob_elmo_homing/))

I will try, thanks.

**Comment by mathias-luedtke** [comment]
@ye-luo-xi-tui: Did it work?

**Comment by ye-luo-xi-tui** [comment]
> @ye-luo-xi-tui: Did it work?

I tried the second option, it worked well.
