### ISSUE TITLE
Homing failed

### ISSUE THREAD

**Issue by archee8** [ros-industrial/ros_canopen#454]
`[ INFO] [1645085480.296265564]: Current state: 2 device error: system:125 internal_error: 0 (OK)`
`[ INFO] [1645085480.296451906]: Current state: 0 device error: system:125 internal_error: 0 (OK)`
 `[ INFO] [1645085480.297074644]: Current state: 0 device error: system:0 internal_error: 0 (OK) `
`[ INFO] [1645085480.297225639]: Current state: 0 device error: system:0 internal_error: 0 (OK) `                
`[ERROR] [1645085480.297865332]: Initializing failed: homing not attained; Homing failed` 
`success: False`                                          
`message: "homing not attained; Homing failed" `

When I run driver/init I get a homing error, but if I call driver/init again the drive will move and error again, and so on until the home signal is received. Kinco drive is used. In Kinco Servo + if I call homing everything completes without error. How to solve this problem?

**Comment by cschindlbeck** [comment]
This could be related to the timeout problem #433
If the joint is initially too far from the limit switch, it will interrupt the first time due to the timeout. The second time the joint is closer to the limit switch and it will succeed within the default time frame
