### ISSUE TITLE
How to import the EDS files from servo motor manufacturers into the ros_canopen package?

### ISSUE THREAD

**Issue by zouzhe1** [ros-industrial/ros_canopen#477]
How to import the EDS files from servo motor manufacturers into the ros_canopen package? 
I couldn't find a method. 
and where is CSP, CSV, PP, PV. 
Also, how can I optimize the multi-threaded processing? 
Where can I find the instructions for these? 
Why is the README file so brief?

**Comment by mathias-luedtke** [comment]
> Where can I find the instructions for these?
> Why is the README file so brief?

The documentation can be found in http://wiki.ros.org/ros_canopen

> Also, how can I optimize the multi-threaded processing?

There is no multi-threaded processing

> How to import the EDS files from servo motor manufacturers into the ros_canopen package?
> I couldn't find a method.

http://wiki.ros.org/canopen_chain_node#Node_layer

> and where is CSP, CSV, PP, PV.

http://wiki.ros.org/canopen_402#Drive_operation_modes
