### ISSUE TITLE
remove dependency to gazebo

### ISSUE THREAD

**Issue by floweisshardt** [ros-industrial/ros_canopen#51]
currently canopen_test_utils depends on gazebo_ros and gazebo_ros_control. As this package is only used for testing it is not worth to depend on gazebo with the whole repository.

**Comment by mathias-luedtke** [comment]
Can you just remove it from the metapackage and the release?
It it just a package for developing and testing locally, in most cases you need to modify the source anyway.

**Comment by floweisshardt** [comment]
just found a thread (http://answers.ros.org/question/66545/to-ignore-some-pkgs-upon-release-by-bloom/) where it should be possible to ignore a package for bloom. I'll try this.

**Comment by mathias-luedtke** [comment]
Seems to work :)

To get rid of gazebo for robot source overlays, we could discard the corresponding exec_depend lines (and the roslaunch_add_file_check lines for sim files) and state it in the packages description.
The test package is not actively maintained, but still used for maintenance tasks and testing on the test rigs. This is done on workstations with gazebo anyway.

I will migrate some of the helper scripts to other packages.
But I'd like to make them more generic beforehand.

**Comment by floweisshardt** [comment]
solved for the moment. I'll close this
