### ISSUE TITLE
Failure during switch routine

### ISSUE THREAD

**Issue by thiagodefreitas** [ros-industrial/ros_canopen#54]
When the joint limit is reached, e.g. arm_7_joint, and the control_mode_adapter switches back from velocity to trajectory mode, switching fails and the switching service returns false, and by false the controller_manager stays in velocity control mode but the joints that were not in the joint limits,  have already switched to trajectory mode while arm_7_joint  is in error state(joint limits) and thus cannot switch.

The desired behavior would be to do not switch any joint, in case one has an error state.

**Comment by floweisshardt** [comment]
@thiagodefreitas: where does this need to be implemented (package)?

**Comment by mathias-luedtke** [comment]
Will be fixed in the ros-controls stacks, but we need some clean-up on our side as well.
