### ISSUE TITLE
difference between ELMO and SCHUNK

### ISSUE THREAD

**Issue by floweisshardt** [ros-industrial/ros_canopen#67]
in canopen_master/src/node.cpp we currently need

for SCHUNK:

```
        reset();
```

and for ELMO (if more than one module is on the bus):

```
        reset_com();
        emcy_.recover();
```

@thiagodefreitas, @ipa-mdl: please think about a solution which works for both

**Comment by thiagodefreitas** [comment]
For running the test on the cob4-6, I had to do the following changes:
- canopen_master/src/node.cpp
  void Node::init(LayerStatus &status){
     nmt_listener_ = interface_->createMsgListener( can::MsgHeader(0x700 + node_id_), can::CommInterface::FrameDelegate(this, &Node::handleNMT));
  
     sdo_.init();
     try{
        reset_com();
        emcy_.recover();
         prepare();
     } 
     ...
- canopen_master/src/emcy.cpp
  
    void EMCYHandler::read(LayerStatus &status)
    {
    /*
         if(error_register() & (~32)){ // mask device specific error
             status.error("Node has emergency error");
         }
        */

**Comment by mathias-luedtke** [comment]
This disables the error detection (incl. emergency stop) completely!
The EMCY handing and especially the reset need some more work, I will try to find some time for it next week.

**Comment by floweisshardt** [comment]
current state should work with both. needs to be tested

**Comment by mathias-luedtke** [comment]
Current implementation should work for most devices, if not specific issues should be filed.
