### ISSUE TITLE
cob4-6 base crash

### ISSUE THREAD

**Issue by floweisshardt** [ros-industrial/ros_canopen#79]
@ipa-mdl @thiagodefreitas: here are two candumps from the cob4-6 base which crashes very reproducible after a few seconds of operation.

crash directly after init and loading of twist_controller: https://gist.github.com/ipa-fmw/55cc9892ee2c5dc80b5b

crash after driving for some seconds: https://gist.github.com/ipa-fmw/9b8bc16f32f32cc282a3

**Comment by mathias-luedtke** [comment]
Looks like an electrical problem with th CAN bus.

**Comment by floweisshardt** [comment]
nothing software related, I'll close this here
